_BASE_: Base.yaml
MODEL:
  #WEIGHTS: detectron2://ImageNetPretrained/MSRA/R-50.pkl
  MASK_ON: false
  RESNETS:
    DEPTH: 50

DATASETS:
  TRAIN: ("balloon_train",)
  TEST: ("balloon_val",)

SOLVER:
  IMS_PER_BATCH: 2
  MAX_ITER: 300

TEST:
  EVAL_PERIOD: 0